# Based on https://github.com/FabricMC/fabric-example-mod/blob/1.18/.github/workflows/build.yml
name: Java CI with Gradle

on: [ push, pull_request ]

jobs:
  build:
    strategy:
      matrix:
        # Use these Java versions
        java: [
          17,    # Current Java LTS & minimum supported by Minecraft
        ]
        os: [ ubuntu-20.04 ] # You can add windows here if you want to build on that OS as well
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Setup gradlew
        run: gradle wrapper
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: build
        run: make
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts built from latest java on one OS
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: dist/
